### ISSUE TITLE
Out of Date / Update Script

### ISSUE THREAD

**Issue by ranfali** [RequiDev/pubg_external_sdk#1]
Hey mate, if this is an outmated conversion do you have any problem with posting the transformation script as well so we dont need to wait for you to update and can do it ourself and than make a commit.

Thanks for your work.

**Comment by RequiDev** [comment]
This wasn't generated automatically. As said in the README: "Some classes may be outdated, due to many updates since the last time this was updated."

I'm not planning to update it. You can download a dumped (internal) SDK for PUBG from somewhere on UnknownCheats. You'll have to align the offsets by yourself. It's not a big or difficult task. Just annoying.

**Comment by ranfali** [comment]
@RequiDev 
Ok than im sorry i though you generate the normal sdk and than this automaticly like the sdk :/
